version: "2"

linters:
  default: standard
  enable:
    - errcheck
    - staticcheck
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Fprint
        - (io.Closer).Close
        - (*os.File).Close
        - (*database/sql.DB).Close
        - (io.Writer).Write
        - (*database/sql.Row).Scan
        - (*encoding/json.Encoder).Encode
        - (github.com/a-h/templ.Component).Render
        - (*github.com/spf13/viper.Viper).BindPFlag
        - github.com/spf13/viper.BindPFlag
    staticcheck:
      checks:
        - "all"
        - "-ST1000"
        - "-QF1001"
        - "-QF1003"
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
        source: "defer.*\\.Close\\(\\)"
      - linters:
          - errcheck
        source: "\\.Render\\("
    paths:
      - internal/web/templates/*_templ.go
