version: 2

project_name: vecgrep

before:
  hooks:
    - templ generate
    - go mod tidy

builds:
  - id: vecgrep-linux-amd64
    main: ./cmd/vecgrep
    binary: vecgrep
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target x86_64-linux-gnu
      - CXX=zig c++ -target x86_64-linux-gnu
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/abdul-hamid-achik/vecgrep/internal/version.Version={{.Version}}
      - -X github.com/abdul-hamid-achik/vecgrep/internal/version.Commit={{.ShortCommit}}
      - -X github.com/abdul-hamid-achik/vecgrep/internal/version.Date={{.Date}}

  - id: vecgrep-linux-arm64
    main: ./cmd/vecgrep
    binary: vecgrep
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target aarch64-linux-gnu
      - CXX=zig c++ -target aarch64-linux-gnu
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w
      - -X github.com/abdul-hamid-achik/vecgrep/internal/version.Version={{.Version}}
      - -X github.com/abdul-hamid-achik/vecgrep/internal/version.Commit={{.ShortCommit}}
      - -X github.com/abdul-hamid-achik/vecgrep/internal/version.Date={{.Date}}

  - id: vecgrep-darwin-amd64
    main: ./cmd/vecgrep
    binary: vecgrep
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target x86_64-macos
      - CXX=zig c++ -target x86_64-macos
    goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/abdul-hamid-achik/vecgrep/internal/version.Version={{.Version}}
      - -X github.com/abdul-hamid-achik/vecgrep/internal/version.Commit={{.ShortCommit}}
      - -X github.com/abdul-hamid-achik/vecgrep/internal/version.Date={{.Date}}

  - id: vecgrep-darwin-arm64
    main: ./cmd/vecgrep
    binary: vecgrep
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target aarch64-macos
      - CXX=zig c++ -target aarch64-macos
    goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - -s -w
      - -X github.com/abdul-hamid-achik/vecgrep/internal/version.Version={{.Version}}
      - -X github.com/abdul-hamid-achik/vecgrep/internal/version.Commit={{.ShortCommit}}
      - -X github.com/abdul-hamid-achik/vecgrep/internal/version.Date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

brews:
  - name: vecgrep
    repository:
      owner: abdul-hamid-achik
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/abdul-hamid-achik/vecgrep"
    description: "Local-first semantic code search powered by embeddings"
    license: "MIT"
    dependencies:
      - name: ollama
        type: optional
    install: |
      bin.install "vecgrep"
    test: |
      system "#{bin}/vecgrep", "--version"
    skip_upload: "{{ if .Env.HOMEBREW_TAP_TOKEN }}false{{ else }}true{{ end }}"

release:
  github:
    owner: abdul-hamid-achik
    name: vecgrep
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
